### ISSUE TITLE
https -> http -> https for Symbian

### ISSUE THREAD

**Issue by Symbian9** [inaz2/proxy2#11]
Is it possible use proxy like this to connect from device like Symbian S60v3 to HTTPS encrypted with SHA256? I mean as proxy that can run on mobile device locally.
* http://forum.dailymobile.net/forums/symbian-3-symbian-anna-and-nokia-belle-forum/97708-rid-time-certificates-3.html
* http://www.jacco2.dds.nl/networking/symbian_cert_import.html

Currently S60v3 cant install SHA256 certificates, but is it possible implement it using Python, that supported by this platform?

![Nokia N82](http://lh3.ggpht.com/calialive/SLCI5_Wb07I/AAAAAAAACTo/r_RL-TBIEG0/s800/08202008447.jpg)

**Comment by inaz2** [comment]
You can make a SHA-1 CA certificate by the below patch:

```
--- setup_https_intercept.sh    2016-09-23 08:33:23.156824000 +0900
+++ patched/setup_https_intercept.sh    2016-09-27 16:33:56.444312000 +0900
@@ -1,6 +1,6 @@
 #!/bin/sh

 openssl genrsa -out ca.key 2048
-openssl req -new -x509 -days 3650 -key ca.key -out ca.crt -subj "/CN=proxy2 CA"
+openssl req -new -x509 -days 3650 -key ca.key -out ca.crt -subj "/CN=proxy2 CA" -sha1
 openssl genrsa -out cert.key 2048
 mkdir certs/
```

Install ca.crt generated by the patched script :panda_face:

**Comment by inaz2** [comment]
Close because of no reply.
