### ISSUE TITLE
Allow modification of the whole request, not only the body!

### ISSUE THREAD

**Issue by exhuma** [inaz2/proxy2#12]
The functions `request_handler` and `response_handler` only allow modification of the body. It would be good to also allow the request line and headers to be modified.

**Comment by inaz2** [comment]
You can do that. Modify `req.headers` or `res.headers` like below:

```
class YourProxyRequestHandler(ProxyRequestHandler):
    def request_handler(self, req, req_body):
        req.headers['User-Agent'] = 'Mozilla/4.0 (compatible; MSIE 5.01; Windows 98)'
```

**Comment by exhuma** [comment]
The way I understood it, the method "request_rhandler" is supposed to return a new body which is then returned.

I will try this. But I find it questionable that a function has both an "in-place" side-effect *and* returns a value.

**Comment by inaz2** [comment]
req is a instance of BaseHTTPRequestHandler class and it's difficult to replace in instance method.
If you think so, pull request me plz.
