### ISSUE TITLE
Modify response body on https

### ISSUE THREAD

**Issue by khornberg** [inaz2/proxy2#13]
Is it possible to modify the response body from an https endpoint?

I get a `CONNECT` but nothing else. No print I put anywhere shows up either.

**Comment by inaz2** [comment]
Did you read README.md?

```
Enable HTTPS intercept

To intercept HTTPS connections, generate private keys and a private CA certificate:
$ ./setup_https_intercept.sh
Through the proxy, you can access http://proxy2.test/ and install the CA certificate in the browsers.
```

**Comment by khornberg** [comment]
Yes

I did that but needed to use some not-self-signed certs. I copied those over and my requests go through but I'm unable to modify the response. Should I be using `https_transparent`?

**Comment by inaz2** [comment]
You have a corresponding private key and the certificate cannot be a CA, right?

**Comment by inaz2** [comment]
You can't use not-self-signed certs without their corresponding private keys.

**Comment by khornberg** [comment]
Yea, it is on my end. Thanks for the pointers
