### ISSUE TITLE
EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by Bottersnike** [inaz2/proxy2#18]
The proxy script starts fine, but then when I try to access any sites (including proxy2.test) the script spits out the error shown in the title. I have run the sh script but it has not helped.

**Comment by wstierhout** [comment]
@Bottersnike Try visiting http://proxy2.test. For me it didn't work because I didn't add http://

**Comment by Bottersnike** [comment]
Oddly, the proxy file in the examples directory works some of the time and now the main proxy2.py file doesn't appear to even be connecting with my phone..

**Comment by wstierhout** [comment]
I haven't tried the proxy file in the examples directory but the main proxy2.py file works fine for me.

**Comment by inaz2** [comment]
It seems just your environment issue. See #16. 

@wstierhout Thanks for your help.
