### ISSUE TITLE
PUT Requests support

### ISSUE THREAD

**Issue by wstierhout** [inaz2/proxy2#19]
I now get the following error while doing PUT requests through the proxy

`::ffff:37.203.216.12 - - [23/Dec/2016 10:05:11] code 501, message Unsupported method ('PUT')
::ffff:37.203.216.12 - - [23/Dec/2016 10:05:11] "PUT /api/v3/device HTTP/1.1" 501 -
::ffff:37.203.216.12 - - [23/Dec/2016 10:05:11] code 501, message Unsupported method ('PUT')
::ffff:37.203.216.12 - - [23/Dec/2016 10:05:11] "PUT /api/v3/device HTTP/1.1" 501 -`

**Comment by inaz2** [comment]
I implemented it. Check out the latest master branch. Thanks 👍
