### ISSUE TITLE
Open and keeping multiple HTTP/TCP connections open

### ISSUE THREAD

**Issue by jonathankua** [inaz2/proxy2#24]
Hi @inaz2 ,

Thank you for developing proxy2.py, it has been very useful. I'm currently trying to modify your code to support multiple parallel HTTP/TCP connections. The goal is to intercept a HTTP GET request and turns it into multiple (N) GET requests to different parts of the file, then reassemble them before handing it back to the client. I really need to keep N connections open throughput the session to minimise overhead. 

How do I achieve that? Would you mind pointing out where I should modify to open multiple sockets, keep them open, send N GET requests and reassemble them. I tried stepping through the code and modifying do_GET() to issue multiple GET requests, but without any success.

If you could assist me or provide me with some pointers, that would be much appreciated.
Thank you.

Regards,
Jonathan

**Comment by inaz2** [comment]
How about implementing a custom request_handler which sends multiple GET requests, assembles their responses, and self.wfile.write(_assembled_response_) to the client?
If doing this, let the request_handler return None and remove `self.send_error(403)` in [L132](https://github.com/inaz2/proxy2/blob/212e90f29ce4fa06c3796613281a0d6751214f88/proxy2.py#L132) not to send a unnecessary 403 response.

**Comment by jonathankua** [comment]
Thanks for your prompt reply @inaz2 . Do we need to explicitly open multiple sockets or does the rest of the code look after that after we implement a custom request_handler

I identify this line of code responsible for opening non SSL connection:
`self.tls.conns[origin] = httplib.HTTPConnection(netloc, timeout=self.timeout)`

Do we need a loop to create multiple httplib.HTTPConnection objects? 
And how do we reassemble the responses if they do not return in order?

Thanks for your help.

Regards,
Jonathan

**Comment by inaz2** [comment]
I suggest you to use Pool.map() in [multiprocessing module](https://docs.python.org/2/library/multiprocessing.html) 🤞

**Comment by jonathankua** [comment]
Thanks @inaz2 . I'll look into it.

Regards,
Jonathan
