### ISSUE TITLE
how does the `self.tls.conn_pool` work?

### ISSUE THREAD

**Issue by yifeikong** [inaz2/proxy2#26]
AFAIK, the server class create a new instance of RequestHandler per request, `self.tls.conn_pool` is a member of the RequestHandler class, how does it works?

I tested a bit

```
In [10]: class Foo:
    ...:     def __init__(self):
    ...:         import threading
    ...:         self.local = threading.local()
    ...:         self.local.vars = {}
    ...:
    ...:

In [11]: f = Foo()

In [12]: f.local.vars
Out[12]: {}

In [13]: g = Foo()

In [14]: f.local.vars['a'] = 'a'

In [15]: g.local.vars
Out[15]: {}
```

**Comment by inaz2** [comment]
> the server class create a new instance of RequestHandler per request

In HTTP/1.1, multiple requests sends in one connection.
The server class create a new instance "per connection", not "per request".

For example, the client sends below requests in sequence in one connection:

- a request to www.example.com (A1)
- a request to www.example.net (B1)
- another request to www.example.com (A2)

To reuse the connection of A1 for A2, ProxyRequestHandler uses `self.tls.conns` dictionary.
When it handles A1, it keeps the connection in the dictionary.
Then it reuse the connection in the dictionary for A2.

proxy2 uses ThreadingHTTPServer that handles each connection in each thread, the dictionary must be a thread-local variable.
This is why `threading.local()` is used.

**Comment by yifeikong** [comment]
> * a request to www.example.com (A1)
> * a request to www.example.net (B1)
> * another request to www.example.com (A2)

For connecting to site A, there will be an instance that handles both A1 and A2, but the the handler instance only handles requests for site A, which is example.com. So there will be only 2 item in `self.tls.conn`: `('http', 'example.com'), ('https', 'example.com')`, am I correct?

**Comment by inaz2** [comment]
No, a single connection can carry requests for any sites. How to use a connection is determined by the client (i.e. web browsers). I suggest you to analyze the packets between the browser and the proxy by using Wireshark.

**Comment by yifeikong** [comment]
ok, I see what you mean, the proxy is a server to the clients, so they will try to reuse the connection between themselves and the proxy, so different requests to different sites will be going through the same handler, which makes `self.tls.pool` useful.

Thanks for your explain!

**Comment by inaz2** [comment]
You're welcome 😺
