### ISSUE TITLE
How  to bind  to a single address instead of all network interfaces by default

### ISSUE THREAD

**Issue by JoePython1** [inaz2/proxy2#30]
How  to bind  to a single address instead of all network interfaces in that host by default

For eg. Is there a  way to specify?

```bash
python proxy2.py 127.0.0.1:3128

**Comment by inaz2** [comment]
Currently such invocation is not supported.

You can edit the below line or implement customized test() function.
https://github.com/inaz2/proxy2/blob/e8fd304717c70cd39363858b4e6f2d591aaec577/proxy2.py#L375
