### ISSUE TITLE
POST wrong

### ISSUE THREAD

**Issue by sonlia** [inaz2/proxy2#4]
hi  when i post  to dowload data 

27.0.0.1 - - [31/Mar/2016 23:05:30] code 400, message Bad HTTP/0.9 request type ('Content-Length:')
::ffff:127.0.0.1 - - [31/Mar/2016 23:05:30] "Content-Length: 63" 400 -

**Comment by inaz2** [comment]
It seems that you send wrong HTTP request line :confused:
It should be either of `POST /foobar HTTP/1.0` or `POST /foobar HTTP/1.1`.
Check what you sent to proxy2 server.

**Comment by sonlia** [comment]
POST http://www.bttiantang.com/download.php HTTP/1.1
Accept: */*
Proxy-Connection: Keep-Alive
Content-Type: application/x-www-form-urlencoded
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; WOW64; Avant Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; InfoPath.1; .NET CLR 3.5.30729; .NET CLR 3.0.30618) 
Host: www.bttiantang.com

HTTP/1.1 200 OK
Server: nginx/1.2.9
Date: Tue, 05 Apr 2016 15:26:10 GMT
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
X-Powered-By: PHP/5.2.17p1
Content-Encoding: gzip

::ffff:127.0.0.1 - - [05/Apr/2016 23:23:24] code 400, message Bad HTTP/0.9 request type ('Content-Length:')
::ffff:127.0.0.1 - - [05/Apr/2016 23:23:24] "Content-Length: 64" 400 -



I am confused，and want get the torrent file 
http://www.bttiantang.com/download.php?temp=yes&id=27871&uhash=05043b3a7b498dd1ad68406a

**Comment by inaz2** [comment]
The request is bad. It's not this project's issue. Close.

**Comment by inaz2** [comment]
#16
