### ISSUE TITLE
Does not work properly with stream URLs

### ISSUE THREAD

**Issue by vladkorotnev** [inaz2/proxy2#5]
The proxy gets stuck when a user tries to open a stream, such as a video broadcast or an internet radio stream.

In order to have streaming work, it is necessary to move the sending routines up into the reading routines. 

i.e. change lines 160 to 180 like so:

```
            setattr(res, 'headers', res.msg)
            setattr(res, 'response_version', version_table[res.version])
            res_headers = self.filter_headers(res.headers)

            self.wfile.write("%s %d %s\r\n" % (self.protocol_version, res.status, res.reason))
            for line in res_headers.headers:
                self.wfile.write(line)
            self.end_headers()
            re = res.read(1024)
            while re:
                self.wfile.write(re)
                self.wfile.flush()
                re = res.read(1024)
```

**Comment by inaz2** [comment]
i see, but i think response_handler should be ignored in such case.
give me some example urls (or response headers text) that the proxy stuck :pray:

**Comment by vladkorotnev** [comment]
Try running anything like an internet radio, i.e. http://www.happyhardcore.com/radio/player/radio.asp — when you try to listen to the stream, it never loads to the point of playing, because the proxy buffers everything to itself and not letting anything through.

Yes, the response_handler is hard to implement in such a use case.

I will upload my project with the necessary streaming changes to my Bitbucket and show it later today :)

**Comment by inaz2** [comment]
Changed to handle the response as streaming content if Content-Length response header is absent and Cache-Control response headers contains "no-store". Close.
