### ISSUE TITLE
code 400, Bad Request

### ISSUE THREAD

**Issue by 0xmtn** [inaz2/proxy2#7]
I get this on both HTTP and HTTPS:

> ::ffff:192.168.19.57 - - [31/May/2016 11:47:39] code 400, message Bad request syntax ("\x16\x03\x01\x00\xdf\x01\x00\x00\xdb\x03\x03WMy\xdbq\xcb\x97\xeb\xe6{\x05\x19\x8c\xf5\xbd\x18\x8c0#k\x03\xdfk\x85\x87\xa1\xb5\x9bA7v'\x00\x004\x00\xff\xc0,\xc0+\xc0$\xc0#\xc0")
> ::ffff:192.168.19.57 - - [31/May/2016 11:47:39] "??WMy?q˗??{????0#k?k?????A7v'4??,?+?$?#?" 400 -
> 

I generated the certificate using the .sh script. I'm also using openwrt as OS. What am I doing wrong?

**Comment by inaz2** [comment]
It's not this project's issue. Close.

**Comment by inaz2** [comment]
#16
