### ISSUE TITLE
proxy2_https

### ISSUE THREAD

**Issue by denizyesilirmak** [inaz2/proxy2#8]
I couldn't get this work. :tired_face: 
I generated ssl certificate with your script. It says "serving ssl proxy on 3129" but it doesnt work.

**Comment by inaz2** [comment]
proxy2_https.py is for transparent HTTPS proxy. Use proxy2.py and tcp/3128.

**Comment by inaz2** [comment]
I've reverted the default port from 3128 to 8080 (https://github.com/inaz2/proxy2/commit/5303fcfe15f2033abbd5af34797ec885974439a2), please use tcp/8080 instead.
