### ISSUE TITLE
How to abort a request

### ISSUE THREAD

**Issue by langslike** [inaz2/proxy2#9]
I want to abort certain kind of request so that it may never been sent out to the server, but how to do it properly?
I tried to set self.path to "" at the end of my customized request_handler(self, req, req_body) function,  then add an if statement in  the head of do_GET(self) and do noting but simply return.
But the line in do_GET :
assert scheme in ('http', 'https')
always throws an exception.
Hope @inaz2 could leave an email address.

**Comment by inaz2** [comment]
Such action is currently unsupported.
Give me some time for implementing abort_handler(), or please implement it by yourself (pull request is welcome.)

**Comment by inaz2** [comment]
I implemented the feature at 73b85ff.
To abort a request, return `False` in request_handler().
